<b>Whtz, the Bibliophile Kitchen Sink Commander Deck</b>

What if you had every card you could possibly have?

<b> The Commander </b>


Whtz, the Bibliophile {1}{W}{U}

Legendary Creature — Homunculus

Rulebreaker — A deck with this commander has no maximum deck size.

{3} {T}: You draw a card and gain 1 life. This ability costs {3} less to activate if you had 200 or more cards in your starting deck.

1/3

In [1]:
# this deck operates as a giant dataframe, with manipulation by moving specific cards to independent zones(hand,deck, graveyard, exile)

import pandas as pd 
import numpy as np
import scrython


#big list of deck functions, moved into a cell so its easier to see, as i add more functions I'll probably move it out into another python file and import it
def showhand():
    return df.loc[df['Zone']=='Hand']
    
def showboard():
    return df.loc[df['Zone']=='Board']

def showgraveyard():
    return df.loc[df['Zone']=='Graveyard']
    
def showexile():
    return df.loc[df['Zone']=='Exile']

def drawcard(x: int) -> int:
    start = df.loc[df['Zone'] == 'Deck'].iloc[0].name
    df.loc[start:start+x-1, 'Zone'] = 'Hand'
    return df

def shuffledeck(df):
    df = df.sample(frac=1, ignore_index=True)
    return df

def playcard(x: int) -> int:
    df.loc[x,'Zone'] ='Board'

def discard(x: int) -> int:
    df.loc[x,'Zone'] ='Graveyard'
    
def exile(x: int) -> int:
    df.loc[x,'Zone'] ='Exile'

def text(x: int) -> int:
    print(df.at[x, 'Text'])

def reset():
    df['Zone'] = 'Deck'


df = pd.read_csv('whtzfulluwdecklist.csv') #read in the csv
df.head()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,0,_____,Creature — Shapeshifter,{1}{U},{1}: This card's name becomes the card name of...,1,1,Deck
1,1,+2 Mace,Artifact — Equipment,{1}{W},Equipped creature gets +2/+2.\nEquip {3} ({3}:...,NaN,NaN,Deck
2,2,"70,000 Light-Years from Home",Sorcery,{1}{W},Exile target creature or Spacecraft. Its contr...,NaN,NaN,Deck
3,3,"Aang, Airbending Master",Legendary Creature — Human Avatar Ally,{4}{W},"When Aang enters, airbend another target creat...",4,4,Deck
4,4,"Aang, Air Nomad",Legendary Creature — Human Avatar Ally,{3}{W}{W},Flying (This creature can't be blocked except ...,5,4,Deck

In [2]:
df = shuffledeck(df) #shuffle the deck
df.head() #remove this for actual play

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,8125,Mystic Might,Enchantment — Aura,{U},Enchant land you control\nCumulative upkeep {1...,NaN,NaN,Deck
1,2779,Dancer's Chakrams,Artifact — Equipment,{3}{W},"Job select (When this Equipment enters, create...",NaN,NaN,Deck
2,9517,Rapid Prototyper,Artifact — Contraption,NaN,"Whenever you crank this Contraption, create an...",NaN,NaN,Deck
3,2169,Cliffhaven Sell-Sword,Creature — Kor Warrior,{1}{W},NaN,3,1,Deck
4,9157,Precursor Golem,Artifact Creature — Golem,{5},"When this creature enters, create two 3/3 colo...",3,3,Deck

In [3]:
drawcard(7) # draw 7 cards
showhand()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,8125,Mystic Might,Enchantment — Aura,{U},Enchant land you control\nCumulative upkeep {1...,NaN,NaN,Hand
1,2779,Dancer's Chakrams,Artifact — Equipment,{3}{W},"Job select (When this Equipment enters, create...",NaN,NaN,Hand
2,9517,Rapid Prototyper,Artifact — Contraption,NaN,"Whenever you crank this Contraption, create an...",NaN,NaN,Hand
3,2169,Cliffhaven Sell-Sword,Creature — Kor Warrior,{1}{W},NaN,3,1,Hand
4,9157,Precursor Golem,Artifact Creature — Golem,{5},"When this creature enters, create two 3/3 colo...",3,3,Hand
5,8932,Phyrexian Censor,Creature — Phyrexian Wizard,{2}{W},Each player can't cast more than one non-Phyre...,3,3,Hand
6,9952,Riptide Chimera,Enchantment Creature — Chimera,{2}{U},"Flying\nAt the beginning of your upkeep, retur...",3,4,Hand

In [4]:
playcard(3) # play a card by dataframe id

In [5]:
showboard() # see whats on the board

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
3,2169,Cliffhaven Sell-Sword,Creature — Kor Warrior,{1}{W},NaN,3,1,Board

In [6]:
showhand() # look at updated hand

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,8125,Mystic Might,Enchantment — Aura,{U},Enchant land you control\nCumulative upkeep {1...,NaN,NaN,Hand
1,2779,Dancer's Chakrams,Artifact — Equipment,{3}{W},"Job select (When this Equipment enters, create...",NaN,NaN,Hand
2,9517,Rapid Prototyper,Artifact — Contraption,NaN,"Whenever you crank this Contraption, create an...",NaN,NaN,Hand
4,9157,Precursor Golem,Artifact Creature — Golem,{5},"When this creature enters, create two 3/3 colo...",3,3,Hand
5,8932,Phyrexian Censor,Creature — Phyrexian Wizard,{2}{W},Each player can't cast more than one non-Phyre...,3,3,Hand
6,9952,Riptide Chimera,Enchantment Creature — Chimera,{2}{U},"Flying\nAt the beginning of your upkeep, retur...",3,4,Hand

In [7]:
drawcard(1) #draw card when its your turn, then lets see our hand
showhand()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,8125,Mystic Might,Enchantment — Aura,{U},Enchant land you control\nCumulative upkeep {1...,NaN,NaN,Hand
1,2779,Dancer's Chakrams,Artifact — Equipment,{3}{W},"Job select (When this Equipment enters, create...",NaN,NaN,Hand
2,9517,Rapid Prototyper,Artifact — Contraption,NaN,"Whenever you crank this Contraption, create an...",NaN,NaN,Hand
4,9157,Precursor Golem,Artifact Creature — Golem,{5},"When this creature enters, create two 3/3 colo...",3,3,Hand
5,8932,Phyrexian Censor,Creature — Phyrexian Wizard,{2}{W},Each player can't cast more than one non-Phyre...,3,3,Hand
6,9952,Riptide Chimera,Enchantment Creature — Chimera,{2}{U},"Flying\nAt the beginning of your upkeep, retur...",3,4,Hand
7,5538,Herald of Vengeance,Creature — Angel,{3}{W}{W},Flying\nWhen Herald of Vengeance enters the ba...,4,5,Hand

In [8]:
text(7) #get some additional info on this card ID

Flying
When Herald of Vengeance enters the battlefield, destroy each permanent you don't control that has the same name as a permanent that dealt damage to you last turn.