<b>Whtz, the Bibliophile Kitchen Sink Commander Deck</b>

What if you had every card you could possibly have?

<b> The Commander </b>


Whtz, the Bibliophile {1}{W}{U}

Legendary Creature — Homunculus

Rulebreaker — A deck with this commander has no maximum deck size.

{3} {T}: You draw a card and gain 1 life. This ability costs {3} less to activate if you had 200 or more cards in your starting deck.

1/3

In [120]:
import numpy as np
import pandas as pd
import scrython
import deckfunctions


#this operates essentially as a giant dataframe, and manipulation of the zone column lets you know what is where(Board, Deck, Exile, Graveyard, Hand, etc.)
#full list of deck functions is found in deckfunctions.py

#Get every blue/white card via scrython(basic card search rn), and put them into the deck dataframe


results = scrython.cards.Search(q="c<=uw")
print(f"Found {results.total_cards} cards")
deck = []
for card in results.data:
    row = {
        'Name' : card.name,
        'Type' : card.type_line,
        'Cost' : card.mana_cost,
        'Text' : card.oracle_text,
        'Power': card.power,
        'Toughness': card.toughness,
        'Zone' : 'Deck'
    }
    deck.append(row)

#Add Lands to dataframe(50 each)
for i in range(50):
    islands = {
        'Name' : 'Island',
        'Type' : 'Land',
        'Cost' : 0,
        'Text' : 'Land',
        'Zone' : 'Deck'
    }
    plains = {
        'Name' : 'Plains',
        'Type' : 'Land',
        'Cost' : 0,
        'Zone' : 'Deck'
    }
    deck.append(islands)
    deck.append(plains)
    

df = pd.DataFrame(deck)
df.shape

Found 14680 cards

(375, 7)

In [113]:
df= shuffledeck(df)  #shuffle the deck

In [114]:
drawcard(7) # draw 7 cards
showhand()

,Name,Type,Cost,Text,Power,Toughness,Zone
0,Abandoned Air Temple,Land,,This land enters tapped unless you control a b...,NaN,NaN,Hand
1,Island,Land,0,Land,NaN,NaN,Hand
2,Plains,Land,0,NaN,NaN,NaN,Hand
3,Plains,Land,0,NaN,NaN,NaN,Hand
4,Island,Land,0,Land,NaN,NaN,Hand
5,Plains,Land,0,NaN,NaN,NaN,Hand
6,Aegis Turtle,Creature — Turtle,{U},,0,5,Hand

In [115]:
playcard(3) # play a card by dataframe id

In [116]:
showboard() # see whats on the board

     Name  Type Cost Text Power Toughness   Zone
3  Plains  Land    0  NaN   NaN       NaN  Board

In [117]:
showhand() # look at updated hand

,Name,Type,Cost,Text,Power,Toughness,Zone
0,Abandoned Air Temple,Land,,This land enters tapped unless you control a b...,NaN,NaN,Hand
1,Island,Land,0,Land,NaN,NaN,Hand
2,Plains,Land,0,NaN,NaN,NaN,Hand
4,Island,Land,0,Land,NaN,NaN,Hand
5,Plains,Land,0,NaN,NaN,NaN,Hand
6,Aegis Turtle,Creature — Turtle,{U},,0,5,Hand

In [118]:
drawcard(1) #draw card when its your turn, then lets see our hand
showhand()

,Name,Type,Cost,Text,Power,Toughness,Zone
0,Abandoned Air Temple,Land,,This land enters tapped unless you control a b...,NaN,NaN,Hand
1,Island,Land,0,Land,NaN,NaN,Hand
2,Plains,Land,0,NaN,NaN,NaN,Hand
4,Island,Land,0,Land,NaN,NaN,Hand
5,Plains,Land,0,NaN,NaN,NaN,Hand
6,Aegis Turtle,Creature — Turtle,{U},,0,5,Hand
7,Aether Channeler,Creature — Human Wizard,{2}{U},"When this creature enters, choose one —\n• Cre...",2,1,Hand

In [119]:
text(7) #get some additional info on this card ID

When this creature enters, choose one —
• Create a 1/1 white Bird creature token with flying.
• Return another target nonland permanent to its owner's hand.
• Draw a card.