<b>Whtz, the Bibliophile Kitchen Sink Commander Deck</b>

What if you had every card you could possibly have?

<b> The Commander </b>


Whtz, the Bibliophile {1}{W}{U}

Legendary Creature — Homunculus

Rulebreaker — A deck with this commander has no maximum deck size.

{3} {T}: You draw a card and gain 1 life. This ability costs {3} less to activate if you had 200 or more cards in your starting deck.

1/3

In [1]:
# this deck operates as a giant dataframe, with manipulation by moving specific cards to independent zones(hand,deck, graveyard, exile)

import pandas as pd 
import numpy as np


#big list of deck functions, moved into a cell so its easier to see, as i add more functions I'll probably move it out into another python file and import it
def showhand():
    return df.loc[df['Zone']=='Hand']
    
def showboard():
    return df.loc[df['Zone']=='Board']

def showgraveyard():
    return df.loc[df['Zone']=='Graveyard']
    
def showexile():
    return df.loc[df['Zone']=='Exile']

def drawcard(x: int) -> int:
    start = df.loc[df['Zone'] == 'Deck'].iloc[0].name
    df.loc[start:start+x-1, 'Zone'] = 'Hand'
    return df

def addislands(df: pd.DataFrame, x: int) -> pd.DataFrame:
    islands = [
        {
        # Your columns names must match your actual df columns here
            "Unnamed: 0": len(df) + (2 * i),
            "Name": "Island",
            "Type": "Land",
            "Cost": "NaN",
            "Text": "N/A",
            "Power": "NaN",
            "Toughness": "NaN",
            "Zone": "Deck",
        }
        for i in range(x)
    ]

    df = pd.concat([df, pd.DataFrame(islands)], ignore_index=True)
    return df

def addplains(df: pd.DataFrame, x: int) -> pd.DataFrame:
    plains = [
        {
        # Your columns names must match your actual df columns here
            "Unnamed: 0": len(df) + (2 * i),
            "Name": "Plains",
            "Type": "Land",
            "Cost": "NaN",
            "Text": "N/A",
            "Power": "NaN",
            "Toughness": "NaN",
            "Zone": "Deck",
        }
        for i in range(x)
    ]

    df = pd.concat([df, pd.DataFrame(plains)], ignore_index=True)
    return df


def shuffledeck(df):
    df = df.sample(frac=1, ignore_index=True)
    return df

def playcard(x: int) -> int:
    df.loc[x,'Zone'] ='Board'

def discard(x: int) -> int:
    df.loc[x,'Zone'] ='Graveyard'
    
def exile(x: int) -> int:
    df.loc[x,'Zone'] ='Exile'

def text(x: int) -> int:
    print(df.at[x, 'Text'])

def reset():
    df['Zone'] = 'Deck'


df = pd.read_csv('whtzfulluwdecklist.csv') #read in the csv
df.head()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,0,_____,Creature — Shapeshifter,{1}{U},{1}: This card's name becomes the card name of...,1,1,Deck
1,1,+2 Mace,Artifact — Equipment,{1}{W},Equipped creature gets +2/+2.\nEquip {3} ({3}:...,NaN,NaN,Deck
2,2,"70,000 Light-Years from Home",Sorcery,{1}{W},Exile target creature or Spacecraft. Its contr...,NaN,NaN,Deck
3,3,"Aang, Airbending Master",Legendary Creature — Human Avatar Ally,{4}{W},"When Aang enters, airbend another target creat...",4,4,Deck
4,4,"Aang, Air Nomad",Legendary Creature — Human Avatar Ally,{3}{W}{W},Flying (This creature can't be blocked except ...,5,4,Deck

In [2]:
# removing duplicates, there are a few cards with duplicate names in the deck that we need to sift out
df = df.drop_duplicates('Name')
duplicates = df[df.duplicated('Name')]
duplicates

Empty DataFrame
Columns: [Unnamed: 0, Name, Type, Cost, Text, Power, Toughness, Zone]
Index: []

In [4]:
#adding some lands to make this playable, about 7000 total
df = addislands(df,3500)
df = addplains(df,3500)
df.query("Type.str.contains('Land', na=False)")

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
12,12,Abandoned Air Temple,Land,NaN,This land enters tapped unless you control a b...,NaN,NaN,Deck
13,13,Abandoned Campground,Land,NaN,This land enters tapped unless a player has 13...,NaN,NaN,Deck
14,14,Abandoned Outpost,Land,NaN,"This land enters tapped.\n{T}: Add {W}.\n{T}, ...",NaN,NaN,Deck
31,31,Abraded Bluffs,Land — Desert,NaN,This land enters tapped.\nWhen this land enter...,NaN,NaN,Deck
40,40,Abstergo Entertainment,Legendary Land,NaN,"{T}: Add {C}.\n{1}, {T}: Add one mana of any c...",NaN,NaN,Deck
...,...,...,...,...,...,...,...,...
21557,25052,Plains,Land,NaN,N/A,NaN,NaN,Deck
21558,25054,Plains,Land,NaN,N/A,NaN,NaN,Deck
21559,25056,Plains,Land,NaN,N/A,NaN,NaN,Deck
21560,25058,Plains,Land,NaN,N/A,NaN,NaN,Deck
21561,25060,Plains,Land,NaN,N/A,NaN,NaN,Deck

In [5]:
df.shape
#alright its about 38% lands, add more or less as you see fit

(21562, 8)

In [6]:
df = shuffledeck(df) #shuffle the deck
df.head() #remove this for actual play

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,15598,Island,Land,NaN,N/A,NaN,NaN,Deck
1,11101,Skilled Animator,Creature — Human Artificer,{2}{U},"When this creature enters, target artifact you...",1,3,Deck
2,11317,Solar Tide,Sorcery,{4}{W}{W},Choose one —\n• Destroy all creatures with pow...,NaN,NaN,Deck
3,15612,Island,Land,NaN,N/A,NaN,NaN,Deck
4,3708,Elspeth Resplendent,Legendary Planeswalker — Elspeth,{3}{W}{W},+1: Choose up to one target creature. Put a +1...,NaN,NaN,Deck

In [7]:
drawcard(7) # draw 7 cards
showhand()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,15598,Island,Land,NaN,N/A,NaN,NaN,Hand
1,11101,Skilled Animator,Creature — Human Artificer,{2}{U},"When this creature enters, target artifact you...",1,3,Hand
2,11317,Solar Tide,Sorcery,{4}{W}{W},Choose one —\n• Destroy all creatures with pow...,NaN,NaN,Hand
3,15612,Island,Land,NaN,N/A,NaN,NaN,Hand
4,3708,Elspeth Resplendent,Legendary Planeswalker — Elspeth,{3}{W}{W},+1: Choose up to one target creature. Put a +1...,NaN,NaN,Hand
5,18626,Plains,Land,NaN,N/A,NaN,NaN,Hand
6,11592,"Spider-Slayer, Hatred Honed",Legendary Artifact Creature — Human Villain,{2},Whenever Spider-Slayer deals damage to a Spide...,2,1,Hand

In [8]:
playcard(3) # play a card by dataframe id

In [9]:
showboard() # see whats on the board

   Unnamed: 0    Name  Type Cost Text Power Toughness   Zone
3       15612  Island  Land  NaN  N/A   NaN       NaN  Board

In [10]:
showhand() # look at updated hand

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,15598,Island,Land,NaN,N/A,NaN,NaN,Hand
1,11101,Skilled Animator,Creature — Human Artificer,{2}{U},"When this creature enters, target artifact you...",1,3,Hand
2,11317,Solar Tide,Sorcery,{4}{W}{W},Choose one —\n• Destroy all creatures with pow...,NaN,NaN,Hand
4,3708,Elspeth Resplendent,Legendary Planeswalker — Elspeth,{3}{W}{W},+1: Choose up to one target creature. Put a +1...,NaN,NaN,Hand
5,18626,Plains,Land,NaN,N/A,NaN,NaN,Hand
6,11592,"Spider-Slayer, Hatred Honed",Legendary Artifact Creature — Human Villain,{2},Whenever Spider-Slayer deals damage to a Spide...,2,1,Hand

In [11]:
drawcard(1) #draw card when its your turn, then lets see our hand
showhand()

,Unnamed: 0,Name,Type,Cost,Text,Power,Toughness,Zone
0,15598,Island,Land,NaN,N/A,NaN,NaN,Hand
1,11101,Skilled Animator,Creature — Human Artificer,{2}{U},"When this creature enters, target artifact you...",1,3,Hand
2,11317,Solar Tide,Sorcery,{4}{W}{W},Choose one —\n• Destroy all creatures with pow...,NaN,NaN,Hand
4,3708,Elspeth Resplendent,Legendary Planeswalker — Elspeth,{3}{W}{W},+1: Choose up to one target creature. Put a +1...,NaN,NaN,Hand
5,18626,Plains,Land,NaN,N/A,NaN,NaN,Hand
6,11592,"Spider-Slayer, Hatred Honed",Legendary Artifact Creature — Human Villain,{2},Whenever Spider-Slayer deals damage to a Spide...,2,1,Hand
7,12505,Telekinetic Sliver,Creature — Sliver,{2}{U}{U},"All Slivers have ""{T}: Tap target permanent.""",2,2,Hand

In [12]:
text(7) #get some additional info on this card ID

All Slivers have "{T}: Tap target permanent."